//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_Id { get; set; }
        public string Appointment_InfoHeader { get; set; }
        public string Appointment_Info { get; set; }
        public Nullable<int> Appointment_DoctorId { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
    
        public virtual User User { get; set; }
    }
}
