//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string PatientSurname { get; set; }
        public int Patient_IdCard { get; set; }
        public string PatientContact { get; set; }
        public string PatientMail { get; set; }
        public Nullable<byte> PatientAge { get; set; }
        public string PatientAddress { get; set; }
        public Nullable<int> PatientDepartment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
